# 1


In [1]:
from sklearn.datasets import load_iris

# Загрузка датасета
iris = load_iris()

# Просмотр информации о датасете
print("Keys of iris dataset:", iris.keys())
print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)
print("Number of samples:", len(iris.data))
print("Shape of data:", iris.data.shape)


Keys of iris dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
Number of samples: 150
Shape of data: (150, 4)


# 2

In [2]:
from sklearn.model_selection import train_test_split

# Разделение данных на обучающую и валидационную выборки
X_train, X_val, y_train, y_val = train_test_split(iris.data, iris.target, test_size=0.2, random_state=42)

# Вывод индексов разбиения
print("Индексы обучающей выборки:", list(range(len(X_train))))
print("Индексы валидационной выборки:", list(range(len(X_train), len(X_train) + len(X_val))))


Индексы обучающей выборки: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]
Индексы валидационной выборки: [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]


# 3

In [3]:
import numpy as np

# Задаем seed для воспроизводимости
np.random.seed(42)

# Создаем случайную перестановку индексов
permuted_indices = np.random.permutation(len(iris.data))

# Применяем перестановку к данным и меткам
X_permuted = iris.data[permuted_indices]
y_permuted = iris.target[permuted_indices]

# Разделение перемешанных данных на обучающую и валидационную выборки
X_train_permuted, X_val_permuted, y_train_permuted, y_val_permuted = train_test_split(X_permuted, y_permuted, test_size=0.2, random_state=42)

# Вывод индексов разбиения
print("Индексы обучающей выборки (перемешанные):", list(permuted_indices[:len(X_train_permuted)]))
print("Индексы валидационной выборки (перемешанные):", list(permuted_indices[len(X_train_permuted):]))


Индексы обучающей выборки (перемешанные): [73, 18, 118, 78, 76, 31, 64, 141, 68, 82, 110, 12, 36, 9, 19, 56, 104, 69, 55, 132, 29, 127, 26, 128, 131, 145, 108, 143, 45, 30, 22, 15, 65, 11, 42, 146, 51, 27, 4, 32, 142, 85, 86, 16, 10, 81, 133, 137, 75, 109, 96, 105, 66, 0, 122, 67, 28, 40, 44, 60, 123, 24, 25, 23, 94, 39, 95, 117, 47, 97, 113, 33, 138, 101, 62, 84, 148, 53, 5, 93, 111, 49, 35, 80, 77, 34, 114, 7, 43, 70, 98, 120, 83, 134, 135, 89, 8, 13, 119, 125, 3, 17, 38, 72, 136, 6, 112, 100, 2, 63, 54, 126, 50, 115, 46, 139, 61, 147, 79, 59]
Индексы валидационной выборки (перемешанные): [91, 41, 58, 90, 48, 88, 107, 124, 21, 57, 144, 129, 37, 140, 1, 52, 130, 103, 99, 116, 87, 74, 121, 149, 20, 71, 106, 14, 92, 102]


# 4

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

# Обучение модели логистической регрессии
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

# Вывод значений коэффициентов модели
print("Значения коэффициентов модели:", log_reg.coef_)

# Предсказание на тестовом наборе признаков
y_pred = log_reg.predict(X_val)

# Вычисление и вывод метрик accuracy и f1-score
accuracy = accuracy_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("F1-score:", f1)


Значения коэффициентов модели: [[-0.39722629  0.96072669 -2.37394544 -1.00315483]
 [ 0.51273813 -0.25316753 -0.21534804 -0.76917632]
 [-0.11551183 -0.70755916  2.58929348  1.77233116]]
Accuracy: 1.0
F1-score: 1.0


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# 5

In [5]:
# Разделение данных на обучающую и валидационную выборки (новое соотношение 75-25)
X_train_new, X_val_new, y_train_new, y_val_new = train_test_split(iris.data, iris.target, test_size=0.25, random_state=42)

# Обучение модели логистической регрессии на новых данных
log_reg_new = LogisticRegression()
log_reg_new.fit(X_train_new, y_train_new)

# Вывод значений коэффициентов модели для новых данных
print("Значения коэффициентов модели для новых данных:", log_reg_new.coef_)

# Предсказание на валидационном наборе признаков для новых данных
y_pred_new = log_reg_new.predict(X_val_new)

# Вычисление и вывод метрик accuracy и f1-score для новых данных
accuracy_new = accuracy_score(y_val_new, y_pred_new)
f1_new = f1_score(y_val_new, y_pred_new, average='weighted')
print("Accuracy для новых данных:", accuracy_new)
print("F1-score для новых данных:", f1_new)

# Сравнение метрик с предыдущими значениями
print("\nСравнение с предыдущими значениями:")
print("Разница в accuracy:", accuracy_new - accuracy)
print("Разница в F1-score:", f1_new - f1)


Значения коэффициентов модели для новых данных: [[-0.38940007  0.92003796 -2.33104132 -0.98327897]
 [ 0.49945407 -0.30966485 -0.21514522 -0.73398622]
 [-0.110054   -0.61037311  2.54618654  1.71726519]]
Accuracy для новых данных: 1.0
F1-score для новых данных: 1.0

Сравнение с предыдущими значениями:
Разница в accuracy: 0.0
Разница в F1-score: 0.0


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# 6

In [6]:
from sklearn.model_selection import cross_val_score

# Выполнение кросс-валидации модели логистической регрессии
scores = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=5)

# Вывод результатов кросс-валидации
print("Значения метрик accuracy для каждого блока:", scores)
print("Среднее значение метрики accuracy по всем блокам:", scores.mean())


Значения метрик accuracy для каждого блока: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Среднее значение метрики accuracy по всем блокам: 0.9733333333333334


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# 7

In [7]:
from sklearn.model_selection import cross_val_score

# Выполнение кросс-валидации модели логистической регрессии с помощью cross_val_score
scores = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=5)

# Вывод результатов кросс-валидации
print("Значения метрик accuracy для каждого блока:", scores)
print("Среднее значение метрики accuracy по всем блокам:", scores.mean())


Значения метрик accuracy для каждого блока: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Среднее значение метрики accuracy по всем блокам: 0.9733333333333334


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# 8

In [9]:
from sklearn.model_selection import StratifiedKFold

# Создаем объект StratifiedKFold для кросс-валидации с 5 блоками
stratified_kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Создаем модель логистической регрессии
log_reg = LogisticRegression()

# Список для хранения значений accuracy для каждого блока
scores_stratified = []

# Цикл по блокам кросс-валидации
for train_index, test_index in stratified_kfold.split(iris.data, iris.target):
    X_train_stratified, X_test_stratified = iris.data[train_index], iris.data[test_index]
    y_train_stratified, y_test_stratified = iris.target[train_index], iris.target[test_index]
    
    # Обучение модели
    log_reg.fit(X_train_stratified, y_train_stratified)
    
    # Оценка точности на тестовом наборе
    accuracy_stratified = log_reg.score(X_test_stratified, y_test_stratified)
    scores_stratified.append(accuracy_stratified)

# Вывод результатов кросс-валидации с стратификацией
print("Значения метрик accuracy для каждого блока (со стратификацией):", scores_stratified)
print("Среднее значение метрики accuracy по всем блокам (со стратификацией):", np.mean(scores_stratified))


Значения метрик accuracy для каждого блока (со стратификацией): [1.0, 0.9666666666666667, 0.9333333333333333, 1.0, 0.9333333333333333]
Среднее значение метрики accuracy по всем блокам (со стратификацией): 0.9666666666666668


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_re

# 9

In [10]:
from sklearn.model_selection import LeaveOneOut

# Создаем объект LeaveOneOut для кросс-валидации
leave_one_out = LeaveOneOut()

# Создаем модель логистической регрессии
log_reg = LogisticRegression()

# Список для хранения значений accuracy для каждого блока
scores_leave_one_out = []

# Цикл по блокам кросс-валидации
for train_index, test_index in leave_one_out.split(iris.data):
    X_train_loo, X_test_loo = iris.data[train_index], iris.data[test_index]
    y_train_loo, y_test_loo = iris.target[train_index], iris.target[test_index]
    
    # Обучение модели
    log_reg.fit(X_train_loo, y_train_loo)
    
    # Оценка точности на тестовом наборе
    accuracy_leave_one_out = log_reg.score(X_test_loo, y_test_loo)
    scores_leave_one_out.append(accuracy_leave_one_out)

# Вывод результатов кросс-валидации с leave-one-out разбиением
print("Значения метрик accuracy для каждого блока (leave-one-out):", scores_leave_one_out)
print("Среднее значение метрики accuracy по всем блокам (leave-one-out):", np.mean(scores_leave_one_out))


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_re

Значения метрик accuracy для каждого блока (leave-one-out): [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Среднее значение метрики accuracy по всем блокам (leave-one-out): 0.9666666666666667


d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Питон 3.12\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_re